### PR TITLE
Move ssh-agent logic to another package

### PR DESCRIPTION
**Pull request by davidxia**
Move all logic of talking to ssh-agent to another package since that
package can be tested separately and provide extra ssh-agent
functionality. This package simply implements the crtauth Signer
interface.

### CODE REVIEW

**Comment by davidxia** [comment]
FYI @rohansingh @gimaker @mattnworb @nresare

**Comment by mattnworb** [comment]
So this library/jar just wraps `ssh-agent-proxy` now? Feels like overkill to have a lib like this with just one class in it.

**Comment by davidxia** [comment]
Agreed. I can move this to crtauth-Java itself

On Wednesday, October 28, 2015, Matt Brown <notifications@github.com> wrote:

> So this library/jar just wraps ssh-agent-proxy now? Feels like overkill
> to have a lib like this with just one class in it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spotify/crtauth-java-agent-signer/pull/2#issuecomment-151854651>
> .
>


-- 
David Xia
Software Engineer
dxia@spotify.com

**Comment by davidxia** [comment]
@mattnworb I moved it to crtauth-java instead https://github.com/spotify/crtauth-java/pull/40 as it seems to fit better there.

**Pull request merged**
